server:
  port: 8101

spring:
  application:
    name: campus-food-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/campus_food?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Wogua123456789
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
